
x = int(input('enter x: '))
y = int(input('enter y: '))
c = int(input('enter c: '))

print(x + y + c)
print(x * y * c)
print(x / y / c)
print(x - y - c)
print(x + y - c)
print(x * y / c)
print(x + y * c)
print(x / y + c)
print(x - y * c)
print(x / y * c)
print(x + y / c)
print(x / y - c)
print(x - y * c)
print(x * y - c)
print(x * y + c)
print(x - y / c)